BloodBank/BloodBank/urls.py
from django.contrib import admin
from django.urls import path, include
from Myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name = 'index'),
    path('Myapp/', include('Myapp.urls')),

]

BloodBank/Myapp/urls.py
from django.conf.urls import url
from Myapp import views

app_name = 'Myapp'
urlpatterns= [
    url('donorRegisteration/', views.donor, name='donor'),
    url('DonorList/',views.donors, name='donors')

]

BloodBank/Myapp/models.py
from django.db import models

class Donor(models.Model):
    BLOOD_CHOICES = (
    ('O+','O+'),
    ('O-', 'O-'),
    ('A+','A+'),
    ('A-','A-'),
    ('B+','B+'),
    ('B-','B-'),
    ('AB+','AB+'),
    ('AB-','AB-'),
)
    GENDER_CHOICES = (
    ('M','Male'),
    ('F', 'Female'),
    ('O','Others'),
)



    First_Name = models.CharField(max_length = 250)
    Last_Name = models.CharField(max_length = 250)
    Email = models.EmailField(max_length=250,unique = True, blank = True)
    Contact_Number = models.IntegerField(unique=True)
    Blood_Group = models.CharField(max_length=6, choices=BLOOD_CHOICES)
    Gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    Date_of_birth = models.DateField(blank=True)
    Weight = models.IntegerField()
    Address = models.TextField()
    Registered_at = models.DateTimeField(auto_now_add=True, blank = True)

    class Meta:
        verbose_name_plural = "Donor"

    def __str__(self):
        return self.First_Name+ " " + self.Last_Name
class Contact(models.Model):
    Name = models.CharField(max_length = 250)
    Email = models.EmailField(max_length = 250)
    Contact = models.IntegerField()
    Message = models.TextField()
    Date = models.DateTimeField(auto_now_add=True, blank = True)

    class Meta:
        verbose_name_plural = "Contact"

    def __str__(self):
        return self.Name

BloodBank/Myapp/forms.py
from django import forms
from Myapp.models import Donor, Contact
from crispy_forms.helper import FormHelper
class DonorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DonorForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
    class Meta():
        model = Donor
        widgets = {
            'Date_of_birth': forms.DateInput(attrs={'type':'date','class':'form-control'}),

        }
        fields= '__all__'
        helper = FormHelper()
class ContactForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta():
        model = Contact
        fields='__all__'
        helper = FormHelper()

BloodBank/Myapp/views.py
from django.shortcuts import render
from Myapp.forms import DonorForm, ContactForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from Myapp.models import Donor

def index(request):
    data = ContactForm(request.POST)

    if request.method == 'POST':
        data = ContactForm(request.POST)

        if data.is_valid():
            data.save(commit=True)
            return HttpResponse("Thanks")
            print('saved successfully')
            # messages.success(request, 'Form submission successful')


    return render(request,'index.html',{'contact':data})

def donors(request):
    data = Donor.objects.order_by('id')
    return render(request,'donor.html',{'records':data})

def donor(request):
    form = DonorForm

    if request.method == 'POST':
        form = DonorForm(request.POST)

        if form.is_valid():
            form.save(commit = True)
            messages.success(request, 'Form submission successful')
            return HttpResponseRedirect('/')

    return render(request,'donorRegisteration.html',{'form':form})

BloodBank/templates/donorRegisteration.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}
<html>
  <head>
    <title>BLOOD BANK</title>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css"%}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"> -->
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <script>
      $(document).ready(function(){
        $('#id_First_Name').attr("pattern","[A-Za-z]{2,}");
        $('#id_First_Name').attr("title","Please Use Characters only");
        $('#id_Last_Name').attr("pattern","[A-Za-z]{2,}");
        $('#id_Last_Name').attr("title","Please Use Characters only");
        $('#id_Date_of_birth').attr("required","reuired");

      });
   </script>
   <style media="screen">
   div.transbox {
      margin:5%;
      background-color: #ffffff;
      border: 1px solid red;
      opacity: 0.6;
      padding:5%;
      border-radius: 10px;
}
  .link{
    font-size:20px;
    display:inline;
    border-radius:5px;
    color:white;
    margin:10px;
    text-align:center;
  }
  .link:hover{
    color:white;
    font-size:25px;
  }
   </style>
  </head>
  <body style=' background:url("{% static "img/b1.jpg" %}"); background-size:100% 100%; background-attachment:fixed;'>
    <div class="containr-fluid">
      <div class="row bg-light">
        <div class="col-md-4">
          <a href="{% url "index" %}" class="navbar-brand"><span class='line-height:50px;'><span style='color:red;' ><i class="fas fa-tint" style='font-size:50px;'></i><span></a>
        </div>
        <div class='col-md-8 text-right'>
                <a href="{% url "Myapp:donors" %}" style='display:inline-block' class=' nav-link btn btn-outline-warning'> View Donors </a>
                <a href="{% url "index" %}" style='display:inline-block' class='nav-link btn  btn-warning text-white'><i class="fas fa-backward pr-2"></i>Go to Homepage</a>
        </div>
      </div>
      <div class="row h-100 justify-content-center py-5" style="font-family:arial;  background-image: url('{% static 'img/b0.jpg' %}'); background-size:100% 100%; background-attachment:fixed;">
        <div class="col-md-6 transbox">
          <h2 class=' text-dark text-center'>The blood you donate gives someone</h2><h2 class='text-ceneter text-success' style='margin-left:20%;'> another chance at life</h2>
          <h1 class='text-center'>Give the gift of life<br/> <span  style='font-weight:bold; color:red;'>DONATE BLOOD<i class="fas fa-tint" style='font-size:50px;'></i></span></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h1 class='alert-primary text-center py-4 my-2'> <i class="fas fa-tint" style='font-size:50px; color:red;'></i>Fill Out the Form below:<i class="fas fa-tint" style='font-size:50px; color:red;'></i></h1>
        </div>
      </div>
    </div>
    <div class="container h-100  bg-light my-5 py-5" style='border-radius:10px;'>

      <div class="row h-100 justify-content-center align-items-center" >
        <div class="col-md-6 col-sm-12">
          <form  method="post">
          <div class="form-group">
            <table>

              {% crispy form %}
              {% csrf_token %}
            </table>
          </div>
          <div class="form-group">
            <input type="submit" class='btn btn-success' value="Register">
          </div>
        </form>
        </div>
      </div>
    </div>
      <div class="container-fluid text-center" style='margin:0px;'>
        <div class="row">
          <div class="col-md-12" style="padding:0px; background:black; color:white;">
            <strong>Powered By :</strong> <br/> <i class="fa fa-user" style='padding-right:2px;'></i> Sourabh & <br/> <i class="fa fa-user pr-2" style='padding-right:2px;'></i> Reeya<br/>
      			<span class='justify-content-center'>Copyright &copy; <a href="http://www.sachtechsolution.com/" style='color:white;'>Sachtech Solution Pvt. ltd.</a></span>

          </div>
      	</div>
      </div>
  </body>
</html>

BloodBank/templates/index.html
<!DOCTYPE html>
{% extends "nav.html "%}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block body_block %}


<!-- Intro
	================================================== -->
<section id="hero" class="section img-responsive" style="background-image: url('{% static 'img/b0.jpg' %}'); background-size:100% 100%; background:rgba(255,0,0,0.3);">
<div class="container">
	<div class="row">
		<div class="col-md-5 ">
			<div class="herotext mx-auto" style='margin:0 auto;'>
				<h1 class="wow bounceInDown" data-wow-duration="1s" data-wow-delay="0.1s">BLOOD <span class="lighter">BANK</span></h1>
				<p class="lead wow zoomIn" data-wow-duration="2s" data-wow-delay="0.5s">
					When we give cheerfully and accept gratefully, everyone is blessed.
				</p>
				<p>
					<a href="{% url "Myapp:donors"%}" class="btn btn-default btn-lg wow fadeInLeft" role="button"> View Donors </a> &nbsp; <a href="#importance" class="btn btn-default btn-lg wow fadeInRight" role="button">Why Donate???</a>
				</p>
			</div>
		</div>
		<div class="col-md-7">
		</div>
	</div>
</div>
</section>
<!-- About
	================================================== -->
<section id="about" class="parallax section" style="background-image: url('{% static 'img/b1.jpg'%}');">
<div class="wrapsection">
	<div class="parallax-overlay" style="background-color: #01b0d1;opacity:0.9;"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- Title -->
				<div class="maintitle">
					<h3 class="section-title"><strong>Who</strong> We Are</h3>
					<p class="lead">
						There are lot of activities held by us including blood donation camp and awareness camp.
					</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="service-box wow zoomIn" data-wow-duration="1.5s" data-wow-delay="0.1s">
					<img src="{% static "img/camp.jpg"%}" alt="Blood Donation Camp">
					<h3>August 7, 2017 <br/>New York</h3>
					<div class="text-left">
						<p>
							We organized a blood donation camp on August 2017.
						</p>
						<p>
							There were a so many paricipants both donors, as well as  demanders.
						</p>
						<p>
							As Blood is an important resource, both for planned treatments and urgent interventions.
							People can safeguard themselves against cancer and heart attacks by donating blood regularly.

						</p>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="service-box wow flipInY" data-wow-duration="1.5s" data-wow-delay="0.1s">
					<span class="glyphicon glyphicon-stats"></span>
					<h3>Participants</h3>
					<p>
						In light of the predicted shortages in blood supply, it is vital to consider ways in which to maximise donation rates. These include addressing the issue of lower donation rates among ethnic minorities, including Indians.
					</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="service-box wow flipInY" data-wow-duration="1.5s" data-wow-delay="0.2s">
					<span class="glyphicon glyphicon-tree-deciduous"></span>
					<h3>World donor's day</h3>
					<p>
						Every year, on 14 June, countries around the world celebrate World Blood Donor Day. The event serves to thank voluntary, unpaid blood donors for their life-saving gifts of blood and to raise awareness of the need for regular blood donations.				</p>
				</div>

			</div>
			<div class="col-md-4 col-sm-6">
				<div class="service-box wow flipInY" data-wow-duration="1.5s" data-wow-delay="0.3s">
					<span class="glyphicon glyphicon-heart"></span>
					<h3>268 Sponsors</h3>
					<p>
						Sponsers plays an very active role in blood donation process.
					</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="service-box wow flipInY" data-wow-duration="1.5s" data-wow-delay="0.4s">
					<i class="fas fa-tint" style='font-size:50px;'></i>
					<h3> Donated</h3>
					<p>
						The demand for blood and blood products is constant throughout the year, but the reality is that donations drop off in the summer months.
					</p>
				</div>
			</div>
		</div>
		<div class="row mx-0">
			<div class="col-md-12">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3430.056119523614!2d76.69247711440084!3d30.71682269345176!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390fee5a42944be3%3A0xb713d3a3e26a89c1!2sSachTech+Solution+Pvt.+Ltd.!5e0!3m2!1sen!2sin!4v1530452125841" width="100%" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>
	</div>
</div>
</section>

<!-- Random
	================================================== -->
<section class="parallax section" style="background-image: url('{% static 'img/background.jpg' %}');">
	<div class="wrapsection">
	<div class="parallax-overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12 sol-sm-12">
				<div class="maintitle">
					<h3 class="section-title justtitle">Participation is everything</h3>
					<p class="lead bottom0 wow bounceInUp">
						Fusce fermentum lectus id turpis suscipit, ut egestas magna volutpat. Donec a purus tellus. Nunc ut dolor eu est gravida auctor quis vitae.
					</p>
				</div>
			</div>
		</div>
	</div>
	</div>
</section>
<!-- Gallery
	================================================== -->
<section id="gallery" class="parallax section" style="background-image: url('{% static 'img/b2.jpg' %}');">
<div class="wrapsection">
	<div class="parallax-overlay" style="background-color:#00c1c1;opacity:0.9;"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12 sol-sm-12">
				<div class="maintitle">
					<h3 class="section-title">Our Doctors</h3>
					<p class="lead wow flipInX">
						Have a look at our Registered doctors.
					</p>
				</div>
			</div>

			<div class="col-md-4">
				<a href="{% static "img/doct2.jpg" %}" title="Dr. Sherly Coram">
					<img src="{% static "img/doct2.jpg" %}" alt="Dr. Sherly Coram" class="image-responsive">
					<div class="description">
						<span class="caption"> Dr. <strong>Sherly Coram</strong></span>
						<span class="camera"><i class="fa fa-camera"></i></span>
						<div class="clearfix"></div>
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="{% static "img/doct4.jpg" %}" title="Dr. Robt Abram">
					<img src="{% static "img/doct4.jpg" %}" alt="Dr. Robt Abram" class="image-responsive">
					<div class="description">
						<span class="caption">Dr. <strong>Robt Abram</strong></span>
						<span class="camera"><i class="fa fa-camera"></i></span>
						<div class="clearfix"></div>
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="{% static "img/doct5.jpg" %}" title="Dr. Maria Waits">
					<img src="{% static "img/doct5.jpg" %}" alt="Dr. Maria Waits" class="image-responsive">
					<div class="description">
						<span class="caption">Dr.<strong>Maira Waits</strong></span>
						<span class="camera"><i class="fa fa-heart"></i></span>
						<div class="clearfix"></div>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>
</section>
<!-- Text Carousel
	================================================== -->
<section id="slider" class="parallax section" style="background-image: url('{% static 'img/background.jpg' %}');">
<div class="wrapsection">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div id="Carousel" class="carousel slide">
					<ol class="carousel-indicators">
						<li data-target="#Carousel" data-slide-to="0" class="active"></li>
						<li data-target="#Carousel" data-slide-to="1"></li>
						<li data-target="#Carousel" data-slide-to="2"></li>
					</ol>
					<div class="carousel-inner">
						<div class="item active">
							<blockquote>
								<p class="lead">
									You have not lived today until you have done something for someone who can never repay you.
								</p>
								<small>John Bunyan, Marathon</small>
							</blockquote>
						</div>
						<div class="item">
							<blockquote>
								<p class="lead">
									The simplest acts of kindness are by far more powerful then a thousand heads bowing in prayer.
								</p>
								<small>Mahatma Gandhi</small>
							</blockquote>
						</div>
						<div class="item">
							<blockquote>
								<p class="lead">
									There is no exercise better for the heart than reaching down and lifting people up.
								</p>
								<small>John Holmes, Organizer</small>
							</blockquote>
						</div>
					</div>
					<a class="left carousel-control" href="#Carousel" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left"></span>
					</a>
					<a class="right carousel-control" href="#Carousel" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right"></span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
</section>
<!-- FAQ
	================================================== -->
<div class="container" id='faq'>
	<div class="row" >
		<div class="col-md-12" style='margin-top:10%; margin-bottom:10%;'>
			<div class="maintitle">
				<h3 class="section-title" >Who Donate Whom</h3>
				<img src="{% static "img/who.png "%}" alt="Who Donate Whom" height='100%' width='100%'>

			</div>
		</div>
	</div>
</div>
<!-- Random
	================================================== -->
<section class="whitecolor parallax section"  id='importance' style="background-image: url('{% static 'img/5.jpg' %}');">
<div class="wrapsection">
	<div class="container">
	<div class="row">
		<div class="col-md-12 sol-sm-12">
			<div class="maintitle">
				<h3 class="section-title justtitle">Charity <span class="wow flipInX">&amp; love</span> are the same</h3>
				<p class="lead bottom0">
						Donation of Blood means a few minutes to you but a lifetime for somebody else
				</p>
			</div>
		</div>
	</div>
	</div>
</div>
	<div class="container-fluid">
		<div class="row my-5 ">
			<div class="col-md-6 " style='margin:20px 0px 20px 0px'>
				<iframe width="100%" height="315" src="https://www.youtube.com/embed/obXjlquHlhE" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
			</div>
			<div class="col-md-6" style='margin:20px 0px 20px 0px'>
				<iframe width="100%" height="315" src="https://www.youtube.com/embed/oXhsvlUx9fc" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
			</div>
			<div class="col-md-6" style='margin:20px 0px 20px 0px'>
				<iframe width="100%" height="315" src="https://www.youtube.com/embed/E-TNZjMDs1w" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
			</div>
			<div class="col-md-6" style='margin:20px 0px 20px 0px'>
				<iframe width="100%" height="315" src="https://www.youtube.com/embed/HLFzP1D7PKk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
			</div>
		</div>
	</div>
</section>
<!-- Contact
	================================================== -->
<section id="contactarea" class="parallax section" style="background-image: url(http://themepush.com/demo/runcharity/assets/img/map.png);">
<div class="wrapsection">
	<div class="parallax-overlay" style="background-color: #e83a4b;opacity:0.95;"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="maintitle">
					<h3 class="section-title">Get in Touch</h3>
					<p class="lead">
						If you have questions about our events, don't hesitate to send us your message.
					</p>
				</div>
				<form method="post"  onsubmit="myfun()">
					<fieldset>
						<div class="row">
							<div class="col-md-12 wow fadeIn animated animated" data-wow-delay="0.1s" data-wow-duration="2s">
								<table>

		              {% crispy contact %}
		              {% csrf_token %}
		            </table>
								<input type="submit" class='btn btn-secondary' style='background-color:red; color:white; border-radius:10px;' value="POST">
								<script>
									function myfn(){
										alert("Thanks for Your Feedback");
									}
								</script>
								</div>
							</div>
					</fieldset>

				</form>

		</div>
	</div>
</div>
</section>

<div class="container-fluid text-center" style='margin:0px;'>
  <div class="row">
    <div class="col-md-12" style="padding:0px; background:black; color:white;">
      <strong>Powered By :</strong> <br/> <i class="fa fa-user" style='padding-right:2px;'></i> Sourabh & <br/> <i class="fa fa-user pr-2" style='padding-right:2px;'></i> Reeya<br/>
			<span class='justify-content-center'>Copyright &copy; <a href="http://www.sachtechsolution.com/" style='color:white;'>Sachtech Solution Pvt. ltd.</a></span>

    </div>
	</div>
</div>

{% endblock %}

BloodBank/templates/nav.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Meta, title, CSS, favicons, etc. -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>RUN CHARITY </title>

	<!-- Styles -->
	<link rel='stylesheet' href="{% static "css/bootstrap.min.css" %}">
	<link rel='stylesheet' href="{% static "css/animate.min.css" %}">
	<link rel='stylesheet' href="{% static "css/font-awesome.min.css" %}">
	<link rel='stylesheet' href="{% static "css/style.css" %}"/>

	<!-- Fonts -->
<link href='http://fonts.googleapis.com/css?family=Raleway:200,300,400,500,600,700,800' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<!-- Favicon -->
	<link rel="shortcut icon" href="#">
</head>
<body>
<!-- Begin Hero Bg -->
<div id="parallax">
</div>
<!-- End Hero Bg
	================================================== -->
<!-- Start Header
	================================================== -->
<header id="header" class="navbar navbar-expand navbar-inverse navbar-fixed-top" role="banner">
<div class="container-fluid">
	<div class="navbar-header">
		<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		</button>
		<!-- Your Logo -->
		<a href="#hero" class="navbar-brand">BLOOD BANK <span style='color:red;' ><i class="fas fa-tint" style='font-size:50px;'></i><span></a>
	</div>
	<!-- Start Navigation -->
	<nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
	<ul class="nav navbar-nav">
		<li>
		<a href="#hero">Home</a>
		</li>
		<li>
		<a href="#about">About</a>
		</li>
		<li>
		<a href="#gallery">Our Doctors</a>
		</li>
		<li>
		<a href="#slider">Testimonials</a>
		</li>
		<li>
		<a href="#faq">FAQ</a>
		</li>
		<li>
		<a href="#contactarea">Contact</a>
		</li>
		</ul>
		<ul class='navbar-nav ml-auto' style='margin-top:2.5%;'>

		<a class='btn btn-danger nav-link' href="{% url "Myapp:donor" %}"> <i class="fas fa-tint"> </i>Donate Now!!</a>

		</ul>


	</nav>
</div>
</header>

<!-- Credits
=============================================== -->
<!-- Bootstrap core JavaScript
	================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/waypoints.min.js" %}"></script>
<script src="{% static "js/jquery.scrollTo.min.js" %}"></script>
<script src="{% static "js/jquery.localScroll.min.js" %}"></script>
<script src="{% static "jquery.magnific-popup.min.j" %}"></script>
<script src="{% static "js/validate.js" %}"></script>
<script src="{% static "js/common.js" %}"></script>
<script>
	$(document).ready(function(){
		$('#id_Name').attr("pattern","[A-Za-z]{2,}");
		$('#id_Name').attr("title","Please Use Characters only");
	});
</script>
</body>
</html>
{% block body_block %}

{% endblock %}